const {JSDOM}=require('jsdom');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..');
const dom=new JSDOM(fs.readFileSync(path.join(root,'src/main/resources/templates/home.html'),'utf8'),{url:'http://localhost',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;const d=w.document;let edit,loaded,dialogSubmit;
w.WorkspaceCodeEditor=(parent,onChange)=>{edit=onChange;return {load:(name,text)=>{loaded=text;},focus(){}};};
w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
const calls=[];let jobs=0;const requests=new Map();const notices=[];
const project={devices:[{id:'remote',name:'Test',host:'localhost',rootPath:'/home/tester'},{id:'local',name:'Dashboard Server',host:'localhost',rootPath:'/app/data/files'}]};
let content='print("hello")';let revision='v1';let running=false,cancelled=false;
const api=async(url,method,body)=>{
 if(url==='/workspace')return project;
 if(url.endsWith('/inputs')){cancelled=true;return null;}
 if(method==='DELETE'){cancelled=true;return null;}
 if(url.startsWith('/studio/jobs/')&&!method)return {id:'running',state:cancelled?'CANCELLED':'RUNNING',events:[],error:cancelled?'사용자가 중지했습니다.':null};
 if(method==='POST'){calls.push(body);const id=String(++jobs);requests.set(id,body);let result={ok:true};
  if(body.action==='list')result={root:body.root,path:'.',entries:[{name:'project',path:'project',directory:true},{name:'app.py',path:'app.py',directory:false},{name:'<img src=x onerror=alert(1)>',path:'<unsafe>',directory:false}]};
  if(body.action==='read')result={content,revision};
  if(body.action==='save'){assert.equal(body.args.revision,revision);content=body.args.content;revision='v2';result={revision};}
  if(body.action==='git-status')result={branch:'main',branches:['main'],changes:[{index:'M',worktree:' ',path:'staged.ts'},{index:' ',worktree:'M',path:'working.ts'},{index:'U',worktree:'U',path:'conflict.ts'},{index:'?',worktree:'?',path:'new.ts'}],history:'abc first'};
  if(body.action==='codex-status')result={authenticated:false};
  if(body.action==='codex-account')result={assistant:{authenticated:false}};
  if(body.action==='codex-models')result={assistant:{models:[{id:'test-model',name:'Test',defaultModel:true,defaultEffort:'medium',efforts:[{reasoningEffort:'medium'}]}]}};
  if(body.action==='codex-run')result={assistant:{thread:{id:'thread-1',turns:[{id:'turn-1',items:[{id:'user-1',type:'userMessage',text:body.args.prompt},{id:'answer-1',type:'agentMessage',text:'Result <img src=x>'}]}]}}};
  if(body.action==='codex-thread-new')result={assistant:{thread:{id:'',turns:[]}}};
  if(body.action==='codex-threads')result={assistant:{threads:[{id:'saved-thread',name:'Saved session',updatedAt:100}]}};
  if(body.action==='codex-thread-read')result={assistant:{thread:{id:body.args.threadId,name:'Saved session',turns:[]}}};
  if(body.action==='codex-run'&&running)return {id,state:'RUNNING',events:[]};
  return {id,state:'SUCCEEDED',result,events:body.action==='codex-run'?[{event:'assistant',text:'Result <img src=x>'}]:[]};
 }
 throw new Error('Unexpected request '+url);
};
const tick=()=>new Promise(resolve=>setTimeout(resolve,25));
const click=selector=>{const button=d.querySelector(selector);assert.ok(button,selector);button.click();};
(async()=>{
 w.eval(fs.readFileSync(path.join(root,'src/main/resources/static/js/studio-panels.js'),'utf8'));
 w.eval(fs.readFileSync(path.join(root,'src/main/resources/static/js/codex-usage.js'),'utf8'));w.eval(fs.readFileSync(path.join(root,'src/main/resources/static/js/studio-codex.js'),'utf8'));
 w.eval(fs.readFileSync(path.join(root,'src/main/resources/static/js/studio.js'),'utf8'));
 w.WorkspaceStudio.init({api,escape:value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),toast:text=>notices.push(text),editor:(title,html,submit)=>{d.querySelector('#editor-fields').innerHTML=html;d.querySelector('#editor-dialog').open=true;dialogSubmit=submit;},openTerminal:async()=>{}});
 await w.WorkspaceStudio.open('studio');
 assert.equal(d.querySelector('#studio-device').value,'local');
 assert.equal(d.querySelector('#studio-root').value,'/app/data/files');
 assert.equal(d.querySelector('#studio-device').options.length,2);
 d.querySelector('.studio-connect').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();
 assert.deepEqual(calls.slice(0,3).map(c=>c.action),['setup','list','git-status']);
 assert.ok(calls.slice(0,3).every(c=>c.deviceId==='local'));
 assert.equal(d.querySelector('.studio-connection').textContent,'서버 자체 · 로컬 실행');
 assert.equal(d.querySelector('.studio-workbench').hidden,false);
 assert.match(d.querySelector('#studio-changes').textContent,/해결이 필요한 충돌/);assert.match(d.querySelector('#studio-changes').textContent,/커밋에 포함될 변경/);assert.match(d.querySelector('#studio-changes').textContent,/작업 폴더 변경/);assert.equal(d.querySelector('[data-studio="git-stage-all"]')!==null,true);
 click('[data-studio="folder-options"]');await tick();assert.equal(d.querySelector('#studio-folder-options option').value,'/app/data/files/project');assert.match(d.querySelector('#studio-folder-status').textContent,/폴더를 검색/);
 assert.equal(d.querySelector('#studio-tree img'),null);
 click('[data-studio="file"][data-path="app.py"]');await tick();assert.equal(loaded,content);
 edit('print("changed")');assert.match(d.querySelector('#studio-dirty').textContent,/저장하지/);
 click('[data-studio="save"]');await tick();assert.equal(content,'print("changed")');assert.equal(calls.filter(c=>c.action==='save').length,1);
 edit('unsaved');click('[data-studio="close"][data-path="app.py"]');await tick();assert.equal(d.querySelector('#editor-dialog').open,true);
 d.querySelector('#editor-dialog').close();await tick();assert.ok(d.querySelector('[data-studio="tab"]'));
 click('[data-studio-panel="codex"]');assert.equal(d.querySelector('#studio-codex').hidden,false);
 d.querySelector('#studio-prompt').value='Review';d.querySelector('#studio-prompt-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();
 assert.equal(calls.some(c=>c.action==='codex-run'),false);assert.ok(notices.some(n=>n.includes('저장')));
 await tick();assert.equal(d.querySelector('#studio-auth-cta').hidden,false);assert.equal(d.querySelector('[data-studio="codex-logout"]').hidden,true);
 click('[data-studio="save"]');await tick();
 d.querySelector('#studio-prompt').value='Review project';d.querySelector('#studio-prompt').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));await tick();
 assert.equal(calls.filter(c=>c.action==='codex-run').length,1);assert.match(d.querySelector('#studio-conversation').textContent,/Result <img/);assert.equal(d.querySelector('#studio-conversation img'),null);assert.equal(d.querySelector('#studio-prompt').value,'');
 click('[data-studio-panel="git"]');click('[data-studio="git-refresh"]');await tick();assert.match(d.querySelector('#studio-conversation').textContent,/Review project/);
 click('[data-studio-panel="codex"]');running=true;d.querySelector('#studio-prompt').value='Cancelable';d.querySelector('#studio-prompt-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(d.querySelector('#studio-prompt').disabled,false);click('#studio-codex [data-cx="stop"]');await new Promise(resolve=>setTimeout(resolve,700));assert.equal(cancelled,true);assert.match(d.querySelector('#cx-status').textContent,/중지/);assert.equal(d.querySelector('#studio-prompt').disabled,false);
 running=false;
 assert.equal(d.querySelector('#studio-codex-model').value,'test-model');
 assert.equal(d.querySelector('#cx-effort').value,'medium');
 click('[data-cx="new"]');await tick();assert.equal(d.querySelector('#cx-title').textContent,'새 세션');
 click('[data-cx="history"]');await tick();assert.match(d.querySelector('#cx-sessions').textContent,/Saved session/);
 click('#cx-sessions button');await tick();assert.equal(d.querySelector('#cx-title').textContent,'Saved session');
 click('[data-cx="file"]');assert.match(d.querySelector('#cx-contexts').textContent,/app.py/);
 d.querySelector('#studio-prompt').value='Continue';d.querySelector('#studio-prompt-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();
 const continuation=calls.filter(c=>c.action==='codex-run').at(-1);assert.equal(continuation.args.threadId,'saved-thread');assert.equal(continuation.args.context[0].path,'app.py');assert.equal(continuation.args.model,'test-model');assert.equal(continuation.args.effort,'medium');
 click('[data-pane="explorer"]');assert.equal(d.querySelector('.studio-workbench').dataset.mobilePane,'explorer');click('[data-pane="editor"]');assert.equal(d.querySelector('.studio-workbench').dataset.mobilePane,'editor');
 d.querySelector('#studio-device').value='remote';
 d.querySelector('#studio-device').dispatchEvent(new w.Event('change'));
 assert.equal(d.querySelector('#studio-root').value,'/home/tester');
 w.eval(fs.readFileSync(path.join(root,'src/main/resources/static/vendor/studio-editor.js'),'utf8'));
 const mount=d.createElement('div');d.body.append(mount);
 const actualEditor=w.WorkspaceCodeEditor(mount,()=>{});
 actualEditor.load('sample.py','print("hello")\n');
 assert.match(mount.querySelector('.cm-content').textContent,/print\("hello"\)/);
 assert.ok(mount.querySelector('.cm-gutters'));
 const workspaceCss=fs.readFileSync(path.join(root,'src/main/resources/static/vendor/workspace-ui.css'),'utf8');
 assert.match(workspaceCss,/#studio-code \.cm-cursor/);
 assert.match(workspaceCss,/caret-color:var\(--accent\)!important/);
 actualEditor.destroy();
 dom.window.close();console.log('PASS: actual CodeMirror bundle mount plus editor connect/bootstrap, escaped file names, tabs, dirty tracking, save, cancel dialog, Codex unsaved guard');
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});
